### PR TITLE
Core property in D9 packages

### PR DESCRIPTION
**Pull request by Pasqualle**
Do not add core property to D9 packages

### CODE REVIEW

**Comment by lkmorlan** [comment]
I wonder if this should be done in doWriteInfoFiles(). That method could pass NULL when it calls rewrite().

**Comment by lkmorlan** [comment]
This fixes #39 .

**Comment by Pasqualle** [comment]
The problem makes info-rewrite unusable, as it creates a fatal error like:
Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' constraint (^8.8 || ^9) requires the 'core' key not be set in modules/contrib/devel/devel.info.yml in Drupal\Core\Extension\InfoParserDynamic->parse() (line 88 of core/lib/Drupal/Core/Extension/InfoParserDynamic.php). 
 
source:
https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/lib/Drupal/Core/Extension/InfoParserDynamic.php#L88

**Comment by Pasqualle** [comment]
hmm. It seems the code is actually correct, there is a hasCoreVersionRequirement() check before adding the core property.
Not sure how I run into this issue, but it seems the problem is not in info-rewrite.

**Comment by lkmorlan** [comment]
It could add a `core` key when one already exists. It only checks for `core_version_requirement`, not `core`.

**Pull request closed without merging**
