### PR TITLE
Write core key only if no core_version_requirement, fixes #22

### LINKED ISSUE #22: core_version_requirement' constraint
I updated the poll module dev version with info-rewrite plugin, but I get the following drush error:

The 'core_version_requirement' constraint (^8.7.7 || ^9) requires the 'core' key not be set in modules/contrib/poll/poll.info.yml

Please not add core key, if core_version_requirement is available.

### PR DESCRIPTION
**Pull request by lkmorlan**
This is the same as #23 with coding standards fixed.

(Is there a way I could have added my commit onto #23 instead of making a new PR? Or did I do it correctly?)

### CODE REVIEW

**Comment by lkmorlan** [comment]
The conditional was backwards. This commit fixes it.

**Comment by geek-merlin** [comment]
Code looks straightforward. (Did not test it though.)

**Comment by jhedstrom** [comment]
> (Is there a way I could have added my commit onto #23 instead of making a new PR? Or did I do it correctly?)

This is the only way I know to make changes to somebody else's PR.

**Comment by jhedstrom** [comment]
Thanks!

**Pull request merged**
